---
title: "Social Media Challenge After Action Report"
author: Kay Endriss, Shelli Temple
date: "June 27, 2017"
output: 
  html_document: 
    theme: cosmo
---
# Social Media Challenge After Action Report #
## United States Conference on Teaching Statistics (USCOTS) ##
## Show Me the DATA! May 18-20, 2017 ##


## Pre-conference Setup ##

### Hashtag ###
#USCOTS17

### Social Media Applications ### 
Twitter, Facebook, Instagram

### Awards ### 
For the social media challenge at USCOTS you can have 10 CAUSE Rewards Points per person entering the challenge (minimum 500, maximum 1000) to give away as prizes. 
 
As examples, if 43 people participate you have 500 points to give out; if 68 people participate you have 680 points to give out; if 127 people participate you have 1000 points to give out.

https://www.causeweb.org/cause/rewards

### Interim Announcement of Leader ### 
yes

### Text for Announcement/Advertising/Program ###
Use Twitter, Instagram, or Facebook.
Share your conference experience and help us accumulate participation data!
 
CAUSE Rewards Program points will be awarded to winners for highest volume of posts and to our top social media “influencer.” Points will then be exchangeable for a variety of statistical prizes.
 
Be sure to get credit for your posts:
Use the conference hashtag: #USCOTS17
Unprotect your tweets; Make sure Instagram is not set to “Private Account”; Make your Facebook posts public.
 
Kickoff: Opening Session, Thursday May 18
Interim Data Look: 4:30 pm Friday May 19--results announced at Banquet
Final Data Analysis: Closing Session, Saturday May 20

## Monitoring During Conference ##

### Tools Used ###
* Google Form https://docs.google.com/forms/d/e/1FAIpQLSekTbV_waPUEQPTw1A5C5ERqGFt6SACJTSnJgVKCmcefQjWVw/viewform
* 
* 

### Comments ###
* Kay writes on May 19: Either didn't have enough sleep last night or caffeine this morning - so I bet I entered some bad dates & times when I started this morning. Any dates you see in now with morning times from yesterday were actually today. And anything entered with time of 9:00AM is likely more between 8:30AM and 9:00AM. Oops, but not really a problem.
* Shelli mentioned on May 19: I had to estimate on times for Facebook and I think some of the people had repeats w/ FB and Twitter crossposting...
* Shelli on May 19: It's going well so far.  The hardest to monitor is Facebook to be honest.  I also noticed that we have some double entries and of course we are on different time zones, so just something to watch for :)
* Shelli on May 20: FYI - @RickyCorp retweeted a lot of his that already had the correct hashtag, so I did not put in the duplicates in the interest of fairness :)

## Data and Analysis ##

### Tools Used ###
* data from Google Form exported to .csv
* JMP
* https://tweetreach.com
  + file no.1 
  + file no.2

### Results ###

### Awards ###
* Rick Corp	160
* Amy Hogan	140
* Glen Russell	60
* Nicholas Horton	60
* Nandy Debmalya	40
* Wendine Bolon	40
* TOTAL	500
```{r}

```

### Comments ###
His name is Debmalya Nandy, not the way it is listed above. Oops.

## Before leaving the conference ##
* Create a Storify archive of the hashtag. 
   (https://storify.com/ekendriss/uscots-2017)

## Notes for Next Time ##
